### ISSUE TITLE
Improving overall UI

### ISSUE THREAD

**Issue by DanonymousCoder** [DanonymousCoder/Random-quotes-generator#13]
Enhance the design using CSS to make the site visually appealing and user-friendly. This includes better typography, spacing, and styling for the dropdown, buttons, and quote display.

**Comment by DmysteriousCoder** [comment]
Can I work on this issue?

**Comment by DanonymousCoder** [comment]
Ok, goodluck

**Comment by DanonymousCoder** [comment]
Solved by PR #14

**Comment by DanonymousCoder** [comment]
Solved by PR #14 for now
