### ISSUE TITLE
Add "Share on Twitter" Functionality

### ISSUE THREAD

**Issue by DanonymousCoder** [DanonymousCoder/Random-quotes-generator#16]
We want to enhance the user experience by allowing users to share their favorite quotes directly on Twitter. This feature will enable users to easily post quotes they love along with a custom message or hashtag.

Acceptance Criteria:

- A "Share on Twitter" button should be added below the quote display.
- When clicked, the button should open a new Twitter share dialog with a pre-filled message that includes the quote and a predefined 
   hashtag (e.g., #QuotesGenerator).
- Ensure the quote text is properly URL-encoded to handle special characters.

**Comment by DmysteriousCoder** [comment]
Can I be assigned this task?

**Comment by DanonymousCoder** [comment]
Solved by PR #17
