### ISSUE TITLE
Add a photo of the individuals behind each quote.

### ISSUE THREAD

**Issue by minsung218** [DanonymousCoder/Random-quotes-generator#27]
Displaying a photo of the person who said the quote alongside the text. This feature will improve the user experience by providing more context and visual engagement.

**Comment by dohyun123** [comment]
Can I work on this issue ?

**Comment by DanonymousCoder** [comment]
@minsung218  Would you like to work on this issue?

**Comment by minsung218** [comment]
@DanonymousCoder Yes!!

**Comment by DanonymousCoder** [comment]
Ok, fire on! and don't forget to star the repo!!
