### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by DanonymousCoder** [DanonymousCoder/Random-quotes-generator#28]
Overall or little tweaks in the UI

**Comment by therurouni** [comment]
Hii @DanonymousCoder.I would like to work on this issue.Can u please assign this issue to me

**Comment by patricksolka** [comment]
Hello, I would like to work on this issue. Am I allowed to use frameworks?

**Comment by DanonymousCoder** [comment]
Yes sure, you can go ahead! @PAVAN507-STAR
