### ISSUE TITLE
Add a new category of quotes (e.g., motivational, funny, etc.)

### ISSUE THREAD

**Issue by DanonymousCoder** [DanonymousCoder/Random-quotes-generator#3]
Add functionality for different categories of quotes, such as motivational, funny, inspirational, etc. Users should be able to select a category and see quotes specific to it.

**Comment by DmysteriousCoder** [comment]
Hi, can I have this assigned to me?

**Comment by DanonymousCoder** [comment]
Sure, fire on

**Comment by DanonymousCoder** [comment]
Solved by PR #9 & #10
