### ISSUE TITLE
Add a like feature

### ISSUE THREAD

**Issue by leejieun0000** [DanonymousCoder/Random-quotes-generator#34]
Add a feature that allows users to view liked quotes on a 'like' page by pressing the like button on generated quotes.

**Comment by leejieun0000** [comment]
Can I work on this issue?

**Comment by DanonymousCoder** [comment]
Yh, sure. You can go ahead

**Comment by leejieun0000** [comment]
Please assign.

**Comment by DanonymousCoder** [comment]
Sorry, totally forgot
