### ISSUE TITLE
Add a "Copy to Clipboard" button to copy quotes

### ISSUE THREAD

**Issue by DanonymousCoder** [DanonymousCoder/Random-quotes-generator#5]
Add a button that allows users to copy the displayed quote to their clipboard. This will make it easier for users to share the quotes.

**Comment by South-IN** [comment]
Can I work on this issue ?

**Comment by DanonymousCoder** [comment]
Sure. How would you go about it?

**Comment by South-IN** [comment]
One way I can do it is with a button next to the quote field.On click of the button I can handle the event by taking the data from the quote field and putting it in the clipboard.

**Comment by DanonymousCoder** [comment]
Ok, fire on 🔥

**Comment by South-IN** [comment]
@DanonymousCoder is there some work left in this issue ?
