### ISSUE TITLE
Implement a typewriter effect for the quote display

### ISSUE THREAD

**Issue by DanonymousCoder** [DanonymousCoder/Random-quotes-generator#6]
Add a typewriter effect so that when a new quote is generated, it types out the characters one by one, creating a cool animation effect.

**Comment by DmysteriousCoder** [comment]
Hi, can this issue be assigned to me?

**Comment by DanonymousCoder** [comment]
Sure, how would you solve this?

**Comment by DmysteriousCoder** [comment]
To create a typewriter effect for the quotes, you'll use JavaScript to display each character of a quote one by one. First, clear the previous quote, then loop through the new quote's characters, showing each one with a small delay using the `setTimeout` function. A recursive function is used to repeatedly call itself, adding one letter at a time to the display until the full quote is shown, creating the typewriter animation.

**Comment by DanonymousCoder** [comment]
Ok, fire on then 🔥

**Comment by DanonymousCoder** [comment]
Solved by PR #8
