### ISSUE TITLE
Improve the dark mode styling

### ISSUE THREAD

**Issue by DanonymousCoder** [DanonymousCoder/Random-quotes-generator#7]
Refine the existing dark mode, ensuring the colors and user experience are cohesive, and make adjustments to the typography, background, and button styles to look great in dark mode.

**Comment by saikatsardar01** [comment]
I would like to work on this issue

**Comment by DmysteriousCoder** [comment]
Can I be assigned this issue?

**Comment by DanonymousCoder** [comment]
How do you want to go about it?

**Comment by saikatsardar01** [comment]
Before :-

![Screenshot 2024-10-06 075615](https://github.com/user-attachments/assets/82c9d270-a583-4dff-9c92-dc92e8035175)

After :-

![Screenshot 2024-10-06 075706](https://github.com/user-attachments/assets/0e6532bf-8413-4740-ab17-8e993a98fc50)

**Comment by DanonymousCoder** [comment]
I've you synced to the latest codebase? If so, create a PR
